from snakemake.utils import min_version
import pandas as pd
from os.path import dirname, basename
from pathlib import Path
import scripts.gather_fastq

min_version("8.0")

configfile: "config/config.yaml"
localrules: all, multiqc, tabulate_flnc, fetch_SQANTI3_CAGE_peaks # needs to be executed on login node to download packages...

samples = pd.read_csv(config["samples"], sep = ' ').set_index("sample", drop=False)
print(samples)
short_read_samples = pd.read_csv(config["star_rsem"]["samples"], sep = ' ').set_index("sample", drop=False)
print(short_read_samples)

# targeting...
rule all:
    input:
        "results/merged/merged_ref_isoseq.sorted.gtf",
        expand("results/rsem/{sample}/{sample}.isoforms.results", sample = short_read_samples.index),
        "results/rsem-combined/isoseq_rsem_transcripts.tsv",
        "results/star_index_isoseq",
        "results/multiqc/multiqc-report.html"

module star_rsem:
    snakefile: github("alecpnkw/star-rsem", path="workflow/Snakefile", branch="dev")
    config: config["star_rsem"]

use rule star_index from star_rsem as sr_star_index with:
    input: 
        fasta = config["reference"],
        gtf = "results/merged/merged_ref_isoseq.gtf"
    output:
        directory("results/star_index_isoseq")

use rule star_pe_single from star_rsem as sr_star_pe_single with:
    input:
        genome = "results/star_index_isoseq",
        R1 = lambda wc: short_read_samples.loc[wc.sample, "R1_fastq"], # directs to fastq files
        R2 = lambda wc: short_read_samples.loc[wc.sample, "R2_fastq"]
    params:
        prefix = "results/star-pe/{sample}/",
    output:
        "results/star-pe/{sample}/Aligned.sortedByCoord.out.bam",
        "results/star-pe/{sample}/Aligned.toTranscriptome.out.bam",
        "results/star-pe/{sample}/SJ.out.tab",
        "results/star-pe/{sample}/ReadsPerGene.out.tab"

use rule rsem_prepare_reference from star_rsem as sr_rsem_prepare_reference with:
    input:
        fasta = config["reference"],
        gtf = "results/merged/merged_ref_isoseq.gtf"
    output:
        "results/rsem_index/ref_isoseq.idx.fa"
    params:
        prefix = "results/rsem_index/ref_isoseq"

use rule rsem_calculate_expression from star_rsem as sr_rsem_calculate_expression with:
    input:
        genome = "results/rsem_index/ref_isoseq.idx.fa",
        transcripts = "results/star-pe/{sample}/Aligned.toTranscriptome.out.bam"
    output:
        multiext("results/rsem/{sample}/{sample}", ".isoforms.results", ".genes.results", ".transcript.bam")
    params:
        output_prefix = "results/rsem/{sample}/{sample}",
        genome_prefix = "results/rsem_index/ref_isoseq",
        threads = 16

use rule gather_rsem_transcripts from star_rsem as sr_gather_rsem_transcripts with:
    input:
        expand("results/rsem/{sample}/{sample}.isoforms.results", sample = short_read_samples.index),
    output:
        "results/rsem-combined/isoseq_rsem_transcripts.tsv"
    params:
        samples = short_read_samples.index,
        value = "expected_count",
        key = "transcript_id"

def INPUT_BAM(wc):
	return samples.loc[wc.sample, "input_bam"]

# removing these modules for now and focusing on the PacBio workflow
#include: "rules/map.smk"
#include: "rules/transcriptclean.smk"
#include: "rules/talon.smk"
#include: "rules/sqanti3.smk"
#include: "rules/filter_transcriptome.smk"
include: "rules/multiqc.smk"

# Rules here from the recommended PacBio bulk Iso-Seq workflow: https://isoseq.how/getting-started.html

# unclear what the proper barcoding primer set is here, so defaulting to the v2 set for now...
# the goal here is for demultiplexing and to remove primer sequences
rule lima:
    input: INPUT_BAM
    output:
        "results/lima/{sample}.fl.NEB_5p--NEB_Clontech_3p.bam" # >95% match isoseq v1 clontech primers...
    conda:
        "envs/isoseq.yaml"
    params:
        primers = config["pacbio_primers"],
        base_path = "results/lima/{sample}.fl.bam"
    shell:
        """
        lima {input} {params.primers} {params.base_path} --isoseq --peek-guess
        """

rule isoseq_refine:
    input: "results/lima/{sample}.fl.NEB_5p--NEB_Clontech_3p.bam"
    output: "results/isoseq_refine/{sample}.flnc.bam"
    params:
        primers = config["pacbio_primers"]
    conda: 
        "envs/isoseq.yaml"
    shell:
        """
        isoseq refine --require-polya {input} {params.primers} {output}
        """

rule tabulate_flnc:
    input: expand("results/isoseq_refine/{sample}.flnc.bam", sample = samples.index)
    output: "results/isoseq_refine/flnc.fofn"
    shell:
        """
        cd $(dirname {output})
        ls *.flnc.bam > $(basename {output})
        """

# using the new isoseq cluster2 command
# output by default requires support of 2 flnc reads
rule isoseq_cluster:
    input: "results/isoseq_refine/flnc.fofn"
    output:
        "results/isoseq_refine/clustered.bam",
        "results/isoseq_refine/clustered.bam.pbi",
        "results/isoseq_refine/clustered.cluster_report.csv"
    conda: 
        "envs/isoseq.yaml"
    threads: 16
    log: "logs/lsf/isoseq_cluster.log"
    resources:
        mem_mb=128000
    shell:
        """
        isoseq cluster2 {input} {output[0]} > {log} 2>&1
        """

rule pbmm2_align:
    input: 
        ref = config["reference"],
        bam = "results/isoseq_refine/clustered.bam"
    output: "results/pbmm2/mapped.bam"
    conda: 
        "envs/isoseq.yaml"
    threads: 6
    resources:
        mem_mb = 48000
    shell:
        """
        pbmm2 align --preset ISOSEQ --sort -j 12 -m 3000M {input.bam} {input.ref} {output}
        """

rule isoseq_collapse:
    input: "results/pbmm2/mapped.bam"
    output: 
        "results/isoseq_collapse/collapsed.gff",
    conda: 
        "envs/isoseq.yaml"
    shell:
        """
        isoseq collapse --do-not-collapse-extra-5exons {input} {output}
        """

rule fetch_SQANTI3_CAGE_peaks:
    output: "resources/human.refTSS_v3.1.hg38.bed"
    params:
        url = "https://raw.githubusercontent.com/ConesaLab/SQANTI3/refs/heads/master/data/ref_TSS_annotation/human.refTSS_v3.1.hg38.bed"
    shell:
        """
        wget -O {output} {params.url}
        """

rule pigeon_prepare:
    input:
        cage_bed = "resources/human.refTSS_v3.1.hg38.bed",
        collapsed_gff = "results/isoseq_collapse/collapsed.gff",
        annotation = config["annotation"],
        ref_fasta = config["reference"],
    params:
        prefix = "results/pigeon/sample"
    output:
        "results/isoseq_collapse/collapsed.sorted.gff",
        "resources/human.refTSS_v3.1.hg38.sorted.bed"
    conda: 
        "envs/isoseq.yaml"
    shell:
        """
        pigeon prepare {input.annotation} {input.ref_fasta} {input.cage_bed}
        pigeon prepare {input.collapsed_gff}
        """

rule pigeon_classify:
    input:
        cage_bed = "resources/human.refTSS_v3.1.hg38.sorted.bed",
        collapsed_gff = "results/isoseq_collapse/collapsed.sorted.gff",
    params:
        prefix = "results/pigeon/sample",
        annotation = lambda wc: Path(config["annotation"]).with_suffix(".sorted.gtf"),
        ref_fasta = config["reference"]
    output:
        "results/pigeon/sample_classification.txt",
        "results/pigeon/sample_classification.filtered_lite_classification.txt",
        "results/isoseq_collapse/collapsed.sorted.filtered_lite.gff"
    conda: 
        "envs/isoseq.yaml"
    shell:
        """
        pigeon classify {input.collapsed_gff} -o {params.prefix} --cage-peak {input.cage_bed} {params.annotation} {params.ref_fasta}
        pigeon filter {output[0]} --isoforms {input.collapsed_gff}
        """
# WIP
rule merge_transcriptome:
    input: "results/isoseq_collapse/collapsed.sorted.filtered_lite.gff"
    output: 
        clean = "results/merged/isoseq.longread.gtf",
        annotated = "results/merged/isoseq.annotated.gtf",
        novel = "results/merged/isoseq_novel.gtf",
        merged = "results/merged/merged_ref_isoseq.gtf",
        merged_sorted = "results/merged/merged_ref_isoseq.sorted.gtf"
        
    params:
        annotation = config["annotation"]
    conda: "envs/gffcompare.yaml"
    shell:
        """
        # ensure is gtf-compatible
        gffread {input} -T -o {output.clean}

        # annotate
        gffcompare -r {params.annotation} -o results/merged/isoseq {output.clean}

        awk -F'\t' '
        BEGIN{{OFS="\t"}}
        $0 ~ /^#/ {{next}}
        # capture class_code from attributes
        {{
            cc = "-"
            if ($9 ~ /class_code "/) {{
            match($9, /class_code "([^"]+)"/, m)
            if (m[1] != "") cc = m[1]
            }}
            # Keep anything that is NOT an exact reference match
            if (cc != "=") print
        }}
        ' {output.annotated} > {output.novel}

        # merge
        cat {params.annotation} {output.novel} > {output.merged}

        # sort
        gffread {output.merged} -E --sort-alpha -o- > {output.merged_sorted}
        """
